# Changes here will be overwritten by Copier
_commit: d6b9241
_src_path: https://github.com/bhklab/bhklab-project-template
author_email: bhklab.jermiahjoseph@gmail.com
author_full_name: Jermiah Joseph
github_username: jjjermiah
project_description: Pipeline to process the PRISM data through the gDR tools and
    PharmacoGx
project_name: PharmacoGx gDR PRISM pipeline
project_slug: pharmacogx-gdr-prism-pipeline
python_version: '3.12'
repo_location: BHKLAB-DataProcessing
