site_name: PharmacoGx gDR PRISM pipeline
repo_url: https://github.com/BHKLAB-DataProcessing/pharmacogx-gdr-prism-pipeline
repo_name: pharmacogx-gdr-prism-pipeline
site_description: Package documentation for PharmacoGx gDR PRISM pipeline
site_author: Jermiah Joseph

# The directory where the documentation files are located
docs_dir: docs

# The directory where the documentation is built (add to .gitignore if changed)
site_dir: site

# This is the branch where the documentation will pushed to using
# 'mkdocs gh-deploy' and from where it will be served by GitHub Pages.
remote_branch: gh-pages

# Address when using 'mkdocs serve', format is 'address:port'
dev_addr: 127.0.0.1:8003

# The layout of the navigation links
nav:
  - Home: index.md
  - Usage: usage.md
  - Data Sources: data_sources.md
  - Developer Notes: devnotes.md

theme: readthedocs

plugins:
    - search                            # necessary for search functionality to work
    - include-markdown                  # allows for including Markdown files into another Markdown file

extra:
    homepage: https://BHKLAB-DataProcessing.github.io/pharmacogx-gdr-prism-pipeline
