
[workspace]
name = "pharmacogx-gdr-prism-pipeline"
authors = ["Jermiah Joseph <bhklab.jermiahjoseph@gmail.com>"]
description = "Pipeline to process the PRISM data through the gDR tools and PharmacoGx"
license = "MIT"
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64"]

[environments]
quality = { features = ["quality"], solve-group = "default" }
docs = { features = ["docs"], solve-group = "default" }

[activation]
# convenient variables which can be used in scripts
env.CONFIG = "${PWD}/config"
env.METADATA = "${PWD}/metadata"
env.LOGS = "${PWD}/logs"
env.RAWDATA = "${PWD}/data/rawdata"
env.PROCDATA = "${PWD}/data/procdata"
env.RESULTS = "${PWD}/data/results"
env.SCRIPTS = "${PWD}/workflow/scripts"

[dependencies]
python = ">=3.12"
ipython = "*"
ipykernel = "*"
jupyterlab = "*"
pip = "*"
r-base = "*"
radian = "*"
r-essentials= "*"
r-devtools = "*"
r-biocmanager = "*"

bioconductor-biocstyle = ">=2.30.0,<3"
bioconductor-biobase = "*"
libcurl = ">=8.10.1,<9"
r-rcurl = "*"
r-rmarkdown = "*"
r-languageserver = ">=0.3.16,<0.4"
bioconductor-gdr = ">=1.4.0,<2"
pandas = ">=2.2.3,<3"

[target.linux-64.dependencies]
# These are not currently available for osx-arm64 so let R/pak install when needed
bioconductor-biomart = "*"
bioconductor-biostrings = "*"
bioconductor-iranges = "*"
r-knitr = "*"

############################################## QUALITY ###############################################
# Quality includes linting, type checking, and formatting
[feature.quality.dependencies]
ruff = "*"

[feature.quality.tasks]
ruff-check.cmd = ["ruff", "check"]
ruff-check.inputs = ["config/ruff.toml", "workflow"]
ruff-check.description = "Run ruff check"

ruff-format.cmd = ["ruff", "format"]
ruff-format.inputs = ["config/ruff.toml", "workflow"]
ruff-format.depends-on = ["ruff-check"]
ruff-format.description = "Run ruff format, run check first"

qc.depends-on = ["ruff-format", "ruff-check"]
qc.description = "Quality check: ruff check and format"

############################################## DOCS ################################################

[feature.docs.dependencies]
mkdocs = "*"
mkdocs-include-markdown-plugin = ">=7.0.0,<8"

[feature.docs.tasks.doc-build]
cmd = "mkdocs build -f mkdocs.yaml"
inputs = ["docs"]
outputs = ["site"]
description = "Build documentation with mkdocs"

[feature.docs.tasks.doc-serve]
cmd = "mkdocs serve -f mkdocs.yaml"
depends-on = ["doc-build"]
inputs = ["docs"]
description = "Serve documentation with mkdocs, runs doc-build first"
